title: MATLAB example
description: >
  This project shows how to incorporate MATLAB into a reproducible
  research project.
# environments:
#   matlab:
#     kind: matlab
#     version: R2024b
#     products:
#       - Statistics_and_Machine_Learning_Toolbox
#       - Parallel_Computing_Toolbox
pipeline:
  stages:
    collect-data:
      kind: matlab-script
      environment: _system
      script_path: scripts/collect_data.m
      outputs:
        - data/raw/data.parquet
    plot-data:
      kind: matlab-script
      environment: _system
      script_path: scripts/plot_data.m
      outputs:
        - figures/plot.png
      inputs:
        - data/raw/data.parquet
datasets:
  - path: data/raw/data.parquet
    title: Raw data
    description: The raw data from the experiment.
    stage: collect-data
figures:
  - path: figures/plot.png
    title: The plot
    description: The plot.
    stage: plot-data
