stages:
  _check-env-matlab:
    cmd: calkit check matlab-env --name matlab --output .calkit/env-locks/matlab.json
    deps: []
    outs:
      - .calkit/env-locks/matlab.json:
          cache: false
          persist: true
    always_changed: true
  collect-data:
    cmd: calkit xenv -n matlab --no-check -- "run('scripts/collect_data.m');"
    deps:
      - scripts/collect_data.m
      - .calkit/env-locks/matlab.json
    outs:
      - data/raw/data.parquet
  plot-data:
    cmd: calkit xenv -n matlab --no-check -- "run('scripts/plot_data.m');"
    deps:
      - scripts/plot_data.m
      - data/raw/data.parquet
      - .calkit/env-locks/matlab.json
    outs:
      - figures/plot.png
